import streamlit as st
import time
import pandas as pd
import os

from optimizer import optimize_tasks
from agent import generate_tasks

st.set_page_config(page_title="Decision Autopilot Agent", layout="wide")

# --- HEADER ---
st.title("🧠 Decision Autopilot Agent")
st.markdown("### Stop deciding. Start executing.")
st.caption("AI Agent + Optimization for intelligent decision-making")

st.markdown("---")

# --- USER INPUT ---
st.header("🤖 Describe Your Situation")

user_input = st.text_area(
    "Example: I have an exam tomorrow but I feel tired and distracted"
)

col1, col2 = st.columns(2)

with col1:
    available_time = st.slider("Available Time (hrs)", 1, 10, 5)

with col2:
    energy_limit = st.slider("Energy Level", 1, 10, 6)

st.markdown("---")

# --- RUN AGENT ---
if st.button("🚀 Run Agent", use_container_width=True):

    if not user_input:
        st.warning("Please describe your situation.")
    else:
        st.toast("Analyzing your situation...")

        with st.spinner("🤖 Thinking like your future self..."):
            time.sleep(1.5)

        tasks = generate_tasks(user_input)

        if not tasks:
            st.error("Agent failed to generate tasks. Try again.")
        else:
            # --- SHOW GENERATED TASKS ---
            st.subheader("📋 Tasks Generated by Agent")
            df_tasks = pd.DataFrame(tasks)
            st.dataframe(df_tasks)

            # --- OPTIMIZATION ---
            selected, rejected = optimize_tasks(
                tasks, available_time, energy_limit
            )

            st.markdown("---")
            st.header("🧠 Decision Plan")

            # 🔥 Main task
            if selected:
                st.success(f"🔥 YOU SHOULD DO: **{selected[0]['name']}**")

            # ✅ Recommended
            st.subheader("✅ Recommended Tasks")
            for t in selected:
                st.write(f"{t['name']} (Score: {t['score']})")

            # ❌ Avoid
            st.subheader("❌ Avoid For Now")
            for t in rejected:
                st.write(t["name"])

            # 📊 Score Chart
            df_tasks["Score"] = [
                t["priority"] + t["regret"] - t["energy"]
                for t in tasks
            ]

            st.markdown("---")
            st.subheader("📊 Decision Score Breakdown")
            st.bar_chart(df_tasks.set_index("name")["Score"])

            # 🧠 Behavior Tracking
            history_file = "history.csv"

            df_selected = pd.DataFrame(selected)

            if os.path.exists(history_file):
                old = pd.read_csv(history_file)
                df_selected = pd.concat([old, df_selected])

            df_selected.to_csv(history_file, index=False)

            # 📈 Insights
            if st.checkbox("📈 Show Behavior Insights"):

                data = pd.read_csv(history_file)

                st.subheader("Behavior Analysis")

                avg_energy = data["energy"].mean()
                avg_priority = data["priority"].mean()

                if avg_energy < 5:
                    st.warning("⚠️ You tend to avoid high-energy tasks")

                if avg_priority > 7:
                    st.success("✅ You focus on high-priority work")

            # 🔮 Wow Feature
            if st.button("🔮 Simulate Future Regret"):
                for t in rejected:
                    st.error(f"If you skip {t['name']}, regret may increase!")
